// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAFeUBkUKQ0mKy6yeQUQzoEqkiB6T1kxU',
    appId: '1:539933488247:android:32c967ec14cdfe9bcf8272',
    messagingSenderId: '539933488247',
    projectId: 'smart-waste-nsbm-30',
    storageBucket: 'smart-waste-nsbm-30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_JZYfbbdWun0S7JssdkyOtIHdxLE6JI',
    appId: '1:539933488247:ios:9c33f3736cc20902cf8272',
    messagingSenderId: '539933488247',
    projectId: 'smart-waste-nsbm-30',
    storageBucket: 'smart-waste-nsbm-30.firebasestorage.app',
    iosBundleId: 'com.example.swmApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXmd7-RolOuCxGadcc33xv5NLA5wqA_LI',
    appId: '1:539933488247:web:75c23f9b8ef3a409cf8272',
    messagingSenderId: '539933488247',
    projectId: 'smart-waste-nsbm-30',
    authDomain: 'smart-waste-nsbm-30.firebaseapp.com',
    storageBucket: 'smart-waste-nsbm-30.firebasestorage.app',
  );
}
